/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fic.h"


void
fic_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int  mulpar2_1_arg;
	void  *result_2;
	struct toto  affichamp_1_arg;
	char * *result_3;
	struct bichaine  concat_1_arg;
	void  *result_4;
	char *plusun_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, FIC, v1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	/*
	mulpar2_1_arg=2;
	result_1 = mulpar2_1(&mulpar2_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("%d\n",*result_1);
	
	toto arg;
	arg.c1=1;
	arg.c2='a';
	affichamp_1_arg=arg;
	result_2 = affichamp_1(&affichamp_1_arg, clnt);
	if (result_2 == (void *) NULL) {
	  clnt_perror (clnt, "call failed"); 
	}

	
	bichaine b;
	strcpy(b.s1,"abc");
	strcpy(b.s2,"def");

	concat_1_arg=b;
	result_3 = concat_1(&concat_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%s\n",*result_3);

	*/

	
	
	result_4 = plusun_1((void*)&plusun_1_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fic_1 (host);
exit (0);
}
