package tabledehach;


/**
* tabledehach/ModifPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tabledehach.idl
* lundi 9 mai 2016 19 h 24 CEST
*/

public abstract class ModifPOA extends org.omg.PortableServer.Servant
 implements tabledehach.ModifOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("containsKey", new java.lang.Integer (0));
    _methods.put ("get", new java.lang.Integer (1));
    _methods.put ("put", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // tabledehach/Modif/containsKey
       {
         int key = in.read_long ();
         boolean $result = false;
         $result = this.containsKey (key);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // tabledehach/Modif/get
       {
         int key = in.read_long ();
         int $result = (int)0;
         $result = this.get (key);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // tabledehach/Modif/put
       {
         int key = in.read_long ();
         int value = in.read_long ();
         this.put (key, value);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tabledehach/Modif:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Modif _this() 
  {
    return ModifHelper.narrow(
    super._this_object());
  }

  public Modif _this(org.omg.CORBA.ORB orb) 
  {
    return ModifHelper.narrow(
    super._this_object(orb));
  }


} // class ModifPOA
