package tabledehach;


/**
* tabledehach/Modif.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tabledehach.idl
* lundi 9 mai 2016 19 h 24 CEST
*/

public interface Modif extends ModifOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Modif
