package tabledehach;


/**
* tabledehach/ModifHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tabledehach.idl
* lundi 9 mai 2016 19 h 24 CEST
*/

abstract public class ModifHelper
{
  private static String  _id = "IDL:tabledehach/Modif:1.0";

  public static void insert (org.omg.CORBA.Any a, tabledehach.Modif that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static tabledehach.Modif extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (tabledehach.ModifHelper.id (), "Modif");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static tabledehach.Modif read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ModifStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, tabledehach.Modif value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static tabledehach.Modif narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof tabledehach.Modif)
      return (tabledehach.Modif)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      tabledehach._ModifStub stub = new tabledehach._ModifStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static tabledehach.Modif unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof tabledehach.Modif)
      return (tabledehach.Modif)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      tabledehach._ModifStub stub = new tabledehach._ModifStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
