package tabledehach;

/**
* tabledehach/ModifHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tabledehach.idl
* lundi 9 mai 2016 19 h 24 CEST
*/

public final class ModifHolder implements org.omg.CORBA.portable.Streamable
{
  public tabledehach.Modif value = null;

  public ModifHolder ()
  {
  }

  public ModifHolder (tabledehach.Modif initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tabledehach.ModifHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tabledehach.ModifHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tabledehach.ModifHelper.type ();
  }

}
