package tabledehach;


/**
* tabledehach/ModifOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tabledehach.idl
* lundi 9 mai 2016 19 h 24 CEST
*/

public interface ModifOperations 
{
  boolean containsKey (int key);
  int get (int key);
  void put (int key, int value);
} // interface ModifOperations
