package cache2;


/**
* cache2/FileSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public interface FileSystem extends FileSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSystem
