package cache2;

/**
* cache2/FileSystemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public final class FileSystemHolder implements org.omg.CORBA.portable.Streamable
{
  public cache2.FileSystem value = null;

  public FileSystemHolder ()
  {
  }

  public FileSystemHolder (cache2.FileSystem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache2.FileSystemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache2.FileSystemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache2.FileSystemHelper.type ();
  }

}
