package calculatrice;


/**
* calculatrice/OperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* lundi 9 mai 2016 17 h 20 CEST
*/

public interface OperationOperations 
{
  float add (float op1, float op2);
  float sub (float op1, float op2);
  float mult (float op1, float op2);
  float div (float op1, float op2) throws calculatrice.DivisionParZeroException;
} // interface OperationOperations
