package calculatrice;

/**
* calculatrice/OperationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* lundi 9 mai 2016 17 h 20 CEST
*/

public final class OperationHolder implements org.omg.CORBA.portable.Streamable
{
  public calculatrice.Operation value = null;

  public OperationHolder ()
  {
  }

  public OperationHolder (calculatrice.Operation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculatrice.OperationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculatrice.OperationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculatrice.OperationHelper.type ();
  }

}
