package calculatrice;


/**
* calculatrice/OperationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculatrice.idl
* lundi 9 mai 2016 17 h 20 CEST
*/

public abstract class OperationPOA extends org.omg.PortableServer.Servant
 implements calculatrice.OperationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("sub", new java.lang.Integer (1));
    _methods.put ("mult", new java.lang.Integer (2));
    _methods.put ("div", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calculatrice/Operation/add
       {
         float op1 = in.read_float ();
         float op2 = in.read_float ();
         float $result = (float)0;
         $result = this.add (op1, op2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // calculatrice/Operation/sub
       {
         float op1 = in.read_float ();
         float op2 = in.read_float ();
         float $result = (float)0;
         $result = this.sub (op1, op2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // calculatrice/Operation/mult
       {
         float op1 = in.read_float ();
         float op2 = in.read_float ();
         float $result = (float)0;
         $result = this.mult (op1, op2);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // calculatrice/Operation/div
       {
         try {
           float op1 = in.read_float ();
           float op2 = in.read_float ();
           float $result = (float)0;
           $result = this.div (op1, op2);
           out = $rh.createReply();
           out.write_float ($result);
         } catch (calculatrice.DivisionParZeroException $ex) {
           out = $rh.createExceptionReply ();
           calculatrice.DivisionParZeroExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calculatrice/Operation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Operation _this() 
  {
    return OperationHelper.narrow(
    super._this_object());
  }

  public Operation _this(org.omg.CORBA.ORB orb) 
  {
    return OperationHelper.narrow(
    super._this_object(orb));
  }


} // class OperationPOA
