package cache2;


/**
* cache2/_FileSystemStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public class _FileSystemStub extends org.omg.CORBA.portable.ObjectImpl implements cache2.FileSystem
{

  public boolean lire (String ref, org.omg.CORBA.StringHolder data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("lire", true);
                cache2.ReferenceHelper.write ($out, ref);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                data.value = cache2.DonneeHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return lire (ref, data        );
            } finally {
                _releaseReply ($in);
            }
  } // lire

  public boolean ecrire (String ref, String data)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ecrire", true);
                cache2.ReferenceHelper.write ($out, ref);
                cache2.DonneeHelper.write ($out, data);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ecrire (ref, data        );
            } finally {
                _releaseReply ($in);
            }
  } // ecrire

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cache2/FileSystem:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _FileSystemStub
