package cache2;


/**
* cache2/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public interface FileSystemOperations 
{
  boolean lire (String ref, org.omg.CORBA.StringHolder data) throws Exception;
  boolean ecrire (String ref, String data) throws Exception;
} // interface FileSystemOperations
