package cache2;

/**
* cache2/IOExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public final class IOExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public cache2.IOException value = null;

  public IOExceptionHolder ()
  {
  }

  public IOExceptionHolder (cache2.IOException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache2.IOExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache2.IOExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache2.IOExceptionHelper.type ();
  }

}
