package monCache2;

/**
* monCache2/DoesNotExistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monCache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public final class DoesNotExistHolder implements org.omg.CORBA.portable.Streamable
{
  public monCache2.DoesNotExist value = null;

  public DoesNotExistHolder ()
  {
  }

  public DoesNotExistHolder (monCache2.DoesNotExist initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = monCache2.DoesNotExistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    monCache2.DoesNotExistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return monCache2.DoesNotExistHelper.type ();
  }

}
