package monCache2;


/**
* monCache2/IOException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monCache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public final class IOException extends org.omg.CORBA.UserException
{

  public IOException ()
  {
    super(IOExceptionHelper.id());
  } // ctor


  public IOException (String $reason)
  {
    super(IOExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class IOException
