package calculatrice;


/**
* calculatrice/fonctionsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex1
* jeudi 17 mars 2016 16 h 52 CET
*/

abstract public class fonctionsHelper
{
  private static String  _id = "IDL:calculatrice/fonctions:1.0";

  public static void insert (org.omg.CORBA.Any a, calculatrice.fonctions that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static calculatrice.fonctions extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (calculatrice.fonctionsHelper.id (), "fonctions");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static calculatrice.fonctions read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_fonctionsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, calculatrice.fonctions value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static calculatrice.fonctions narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculatrice.fonctions)
      return (calculatrice.fonctions)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculatrice._fonctionsStub stub = new calculatrice._fonctionsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static calculatrice.fonctions unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculatrice.fonctions)
      return (calculatrice.fonctions)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculatrice._fonctionsStub stub = new calculatrice._fonctionsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
