package cache;

/**
* cache/DoesNotExistHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 13 mai 2016 15 h 06 CEST
*/

public final class DoesNotExistHolder implements org.omg.CORBA.portable.Streamable
{
  public cache.DoesNotExist value = null;

  public DoesNotExistHolder ()
  {
  }

  public DoesNotExistHolder (cache.DoesNotExist initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache.DoesNotExistHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache.DoesNotExistHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache.DoesNotExistHelper.type ();
  }

}
