package cache;


/**
* cache/FileSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 13 mai 2016 15 h 06 CEST
*/

public interface FileSystem extends FileSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSystem
