package cache;


/**
* cache/IOException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 13 mai 2016 15 h 06 CEST
*/

public final class IOException extends org.omg.CORBA.UserException
{

  public IOException ()
  {
    super(IOExceptionHelper.id());
  } // ctor


  public IOException (String $reason)
  {
    super(IOExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class IOException
