package cache;

/**
* cache/IOExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache.idl
* vendredi 13 mai 2016 15 h 06 CEST
*/

public final class IOExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public cache.IOException value = null;

  public IOExceptionHolder ()
  {
  }

  public IOExceptionHolder (cache.IOException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cache.IOExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    cache.IOExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cache.IOExceptionHelper.type ();
  }

}
