package TME5.calculatrice;


/**
* calculatrice/fonctionsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex1
* jeudi 17 mars 2016 16 h 52 CET
*/

public abstract class fonctionsPOA extends org.omg.PortableServer.Servant
 implements TME5.calculatrice.fonctionsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("sub", new java.lang.Integer (1));
    _methods.put ("mult", new java.lang.Integer (2));
    _methods.put ("div", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calculatrice/fonctions/add
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.add (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // calculatrice/fonctions/sub
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.sub (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 2:  // calculatrice/fonctions/mult
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.mult (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // calculatrice/fonctions/div
       {
         float a = in.read_float ();
         float b = in.read_float ();
         float $result = (float)0;
         $result = this.div (a, b);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calculatrice/fonctions:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public fonctions _this() 
  {
    return fonctionsHelper.narrow(
    super._this_object());
  }

  public fonctions _this(org.omg.CORBA.ORB orb) 
  {
    return fonctionsHelper.narrow(
    super._this_object(orb));
  }


} // class fonctionsPOA
