package TME5.calculatrice;


/**
* calculatrice/fonctionsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex1
* jeudi 17 mars 2016 16 h 52 CET
*/

public interface fonctionsOperations 
{
  float add (float a, float b);
  float sub (float a, float b);
  float mult (float a, float b);
  float div (float a, float b);
} // interface fonctionsOperations
