package TME5.calculatrice;

/**
* calculatrice/fonctionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex1
* jeudi 17 mars 2016 16 h 52 CET
*/

public final class fonctionsHolder implements org.omg.CORBA.portable.Streamable
{
  public TME5.calculatrice.fonctions value = null;

  public fonctionsHolder ()
  {
  }

  public fonctionsHolder (TME5.calculatrice.fonctions initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TME5.calculatrice.fonctionsHelper.read(i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  TME5.calculatrice.fonctionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TME5.calculatrice.fonctionsHelper.type ();
  }

}
