package cache;


/**
* cache/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache/cache.idl
* jeudi 24 mars 2016 16 h 50 CET
*/

public interface FileSystemOperations 
{
  boolean lire (String ref, org.omg.CORBA.StringHolder data);
  boolean ecrire (String ref, String data);
  boolean majCache (String ref, String data);
} // interface FileSystemOperations
