package table;


/**
* table/tabledehachichHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex2
* jeudi 17 mars 2016 18 h 22 CET
*/

abstract public class tabledehachichHelper
{
  private static String  _id = "IDL:table/tabledehachich:1.0";

  public static void insert (org.omg.CORBA.Any a, table.tabledehachich that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static table.tabledehachich extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (table.tabledehachichHelper.id (), "tabledehachich");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static table.tabledehachich read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_tabledehachichStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, table.tabledehachich value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static table.tabledehachich narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof table.tabledehachich)
      return (table.tabledehachich)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      table._tabledehachichStub stub = new table._tabledehachichStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static table.tabledehachich unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof table.tabledehachich)
      return (table.tabledehachich)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      table._tabledehachichStub stub = new table._tabledehachichStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
