package table;


/**
* table/tabledehachichPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex2
* jeudi 17 mars 2016 18 h 22 CET
*/

public abstract class tabledehachichPOA extends org.omg.PortableServer.Servant
 implements table.tabledehachichOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("contains", new java.lang.Integer (0));
    _methods.put ("get", new java.lang.Integer (1));
    _methods.put ("put", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // table/tabledehachich/contains
       {
         String cle = in.read_string ();
         boolean $result = false;
         $result = this.contains (cle);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // table/tabledehachich/get
       {
         String cle = in.read_string ();
         org.omg.CORBA.Object $result = null;
         $result = this.get (cle);
         out = $rh.createReply();
         org.omg.CORBA.ObjectHelper.write (out, $result);
         break;
       }

       case 2:  // table/tabledehachich/put
       {
         String cle = in.read_string ();
         org.omg.CORBA.Object valeur = org.omg.CORBA.ObjectHelper.read (in);
         this.put (cle, valeur);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:table/tabledehachich:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public tabledehachich _this() 
  {
    return tabledehachichHelper.narrow(
    super._this_object());
  }

  public tabledehachich _this(org.omg.CORBA.ORB orb) 
  {
    return tabledehachichHelper.narrow(
    super._this_object(orb));
  }


} // class tabledehachichPOA
