package table;


/**
* table/tabledehachichOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex2
* jeudi 17 mars 2016 18 h 22 CET
*/

public interface tabledehachichOperations 
{
  boolean contains (String cle);
  org.omg.CORBA.Object get (String cle);
  void put (String cle, org.omg.CORBA.Object valeur);
} // interface tabledehachichOperations
