package table;

/**
* table/tabledehachichHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex2
* jeudi 17 mars 2016 18 h 22 CET
*/

public final class tabledehachichHolder implements org.omg.CORBA.portable.Streamable
{
  public table.tabledehachich value = null;

  public tabledehachichHolder ()
  {
  }

  public tabledehachichHolder (table.tabledehachich initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = table.tabledehachichHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    table.tabledehachichHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return table.tabledehachichHelper.type ();
  }

}
