package TME5.table;


/**
* table/tabledehachich.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ex2
* jeudi 17 mars 2016 18 h 22 CET
*/

public interface tabledehachich extends tabledehachichOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface tabledehachich
