package monCache2;

/**
* monCache2/FileSystemCacheHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from monCache2.idl
* jeudi 24 mars 2016 18 h 08 CET
*/

public final class FileSystemCacheHolder implements org.omg.CORBA.portable.Streamable
{
  public monCache2.FileSystemCache value = null;

  public FileSystemCacheHolder ()
  {
  }

  public FileSystemCacheHolder (monCache2.FileSystemCache initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = monCache2.FileSystemCacheHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    monCache2.FileSystemCacheHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return monCache2.FileSystemCacheHelper.type ();
  }

}
