package cache;


/**
* cache/IOException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from cache/cache.idl
* jeudi 24 mars 2016 16 h 50 CET
*/

public final class IOException extends org.omg.CORBA.UserException
{

  public IOException ()
  {
    super(IOExceptionHelper.id());
  } // ctor


  public IOException (String $reason)
  {
    super(IOExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class IOException
